version: "3.8"

services:
  
  mongodb:
    image: mongo:5.0.8
    restart: always
    volumes:
      - COCA_MONGO_DB:/data/db
    env_file: 
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_PORT:-27017}:27017


  server:
    depends_on:
        - mongodb  
    restart: always
    volumes:
      - COCA_SERVER_PUBLIC:/server/public
    image: ${HUB_URL}/${APP_NAME_BACKEND}:${APP_VERSION}
    ports:
      - ${NODE_PORT:-5000}:${NODE_PORT:-5000}
    env_file: 
      - .env

  client:
    image: ${HUB_URL}/${APP_NAME_FRONTEND}:${APP_VERSION}
    ports:
      - ${REACT_PORT:-3000}:80
    env_file: 
      - .env
    environment:
      - VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL}

volumes:
  COCA_MONGO_DB:
  COCA_SERVER_PUBLIC: